version: '2'

services:
  web:
    build: ./sources/.
    ports:
      - "127.0.0.1:8000:8000"
    networks:
      - front-tier
      - back-tier
    env_file: .env
    command: python manage.py runserver 0.0.0.0:8000  # gunicorn _project_.wsgi:application -w 2 -b :8000 --capture-output --enable-stdio-inheritance --log-level=debug --access-logfile=- --log-file=-
    depends_on:
      - postgres
      - redis

#  nginx:
#    build: ./docks/nginx/.
#    ports:
#      - "80:80"
#    volumes:
#      - /www/static
#    volumes_from:
#      - web
#    networks:
#      - front-tier

  postgres:
    image: postgres:9.5.3
    container_name: postgres
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    networks:
      - back-tier

  redis:
    image: redis:3.2.0
    container_name: redis
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redisdata:/data
    networks:
      - back-tier

volumes:
  pgdata:
  redisdata:

networks:
  front-tier:
  back-tier:
