version: '2'

services:
  web:
    build: ./sources/.
    expose:
      - "127.0.0.1:8000:8000"
    networks:
      - front-tier
      - back-tier
#    volumes:
#      - ./sources/_project_/static/:/www/static
    env_file: .env
    command: gunicorn _project_.wsgi:application -w 2 -b :8000
    depends_on:
      - postgres
      - redis

  nginx:
    build: ./nginx/.
    ports:
      - "80:80"
    volumes:
      - /www/static
    volumes_from:
      - web
    networks:
      - front-tier

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    networks:
      - back-tier

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redisdata:/data
    networks:
      - back-tier

volumes:
  pgdata:
  redisdata:

networks:
  front-tier:
  back-tier:
