version: '2'

services:
  web:
    build: ./web/.
    expose:
      - "8000"
    networks:
      - front-tier
      - back-tier
    volumes:
      - ./web:/app
      - ./web/docker_django/static/:/www/static
    env_file: .env
    command: /usr/local/bin/gunicorn docker_django.wsgi:application -w 2 -b :8000

  nginx:
    build: ./nginx/.
    ports:
      - "80:80"
    volumes:
      - /www/static
    volumes_from:
      - web
    networks:
      - front-tier

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    networks:
      - back-tier 

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    networks:
      - back-tier 
      
volumes: 
  pgdata:
  redisdata:

networks:
  front-tier:
  back-tier: